version: '3'

services:
  web:
    image: miladh9999/url-shortener-django:1.0
    container_name: url-shortener-django
    command: "python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
