# Generated by Django 4.1 on 2022-08-31 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urlmap',
            name='short_url',
        ),
    ]
