# Generated by Django 4.1 on 2022-08-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url', '0002_remove_urlmap_short_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlmap',
            old_name='num_clicks',
            new_name='desktop_clicks',
        ),
        migrations.AddField(
            model_name='urlmap',
            name='mobile_clicks',
            field=models.IntegerField(default=0),
        ),
    ]
