# Generated by Django 4.1 on 2022-09-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('times_followed', models.PositiveIntegerField(default=0)),
                ('unique_times_followed', models.PositiveIntegerField(default=0)),
                ('long_url', models.URLField()),
                ('short_url', models.CharField(blank=True, max_length=15, unique=True)),
                ('device', models.CharField(blank=True, max_length=15)),
                ('shortner_owner', models.CharField(blank=True, editable=False, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='VisitUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(blank=True, max_length=15)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('response_date', models.DateTimeField(auto_now_add=True)),
                ('visitor', models.CharField(max_length=20)),
                ('device', models.CharField(max_length=15)),
                ('browser', models.CharField(max_length=15)),
                ('browser_version', models.CharField(max_length=15)),
                ('os', models.CharField(max_length=15)),
                ('os_version', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-visit_date'],
            },
        ),
    ]
