version: '3.7'

services:
  django_gunicorn:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8001:8001"
  nginx:
    build: ./nginx
    volumes:
      - static:/static
    ports:
      - "91:91"
    depends_on:
      - django_gunicorn

volumes:
  static:

