version: '3.5'

services:
    app:
        restart: always
        build: .
        tty: true
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        env_file:
            - ./.env
        stdin_open: true